github :
   prebuilds :
     # 마스터/기본 브랜치 활성화(기본값은 true) 
    master : true 
    # 이 리포지토리의 모든 브랜치 활성화(기본값은 false) 
    branch : true 
    # 이 리포지토리에서 오는 풀 리퀘스트 활성화(기본값은 true) 
    pullRequests : true 
    # 포크에서 오는 pull 요청 활성화(기본값은 false) 
    pullRequestsFromForks : true 
    # pull 요청에 대한 주석으로 "Review in Gitpod" 버튼 추가(기본값은 true) 
    addComment : true 
    #요청을 가져오기 위해 "Gitpod에서 검토" 버튼 추가(기본값은 false) 
    addBadge : false 
    # 사전 빌드 가 요청을 가져올 준비가 되면 레이블을 추가합니다(기본값은 false) 
    addLabel : gitpod
