
name: Spring Boot & Gradle CI/CD 

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest   
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: 17
        
    - name: execute gradle
      run: chmod +x ./join/gradlew
    - name: build java
      run: cd ./join  && ./gradlew clean build

