
name: Spring Boot & Gradle CI/CD 

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest   
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: 17
        
    - name: move directory
      run: cd ./join/
      
    - name: list
      run: ls -la ./
      
    - name: pwd
      run: echo `(pwd)`
      
    - name: Grant execute permission for gradlew
      run: chmod +x ./join/gradlew
    
    - name: Build with Gradle
      run: ./join/gradlew clean build
