
name: Spring Boot & Gradle CI/CD 

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest   
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: 17
        
    - name: move directory
      run: cd ./join/ || chmod +x ./gradlew || ./gradlew clean build

