
name: Sign Application Deploy

on:
  workflow_dispatch:
    inputs:
      name:
        description: "RELEASE"
        required: true
        default: "realease v0.1"
jobs:
  build:
    runs-on: ubuntu-latest   
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: 17
        
    - name: execute gradle
      run: chmod +x ./join/gradlew
      
    - name: build java
      run: cd ./join  && ./gradlew clean build
      
    - name: echo
      run: cd ./join/build/libs && ls -la
      
    - name: Jar output
      uses: appleboy/scp-action@master  
      with:
          host: ${{ secrets.REMOTE_IP }}
          username: ${{ secrets.REMOTE_SSH_ID }}
          key: ${{ secrets.REMOTE_SSH_KEY }}
          port: ${{ secrets.REMOTE_SSH_PORT }}
          source: "build/libs/join-0.0.1-SNAPSHOT-plain.jar"
          strip_components: 1
          target: "/home/ubuntu/sign-app"
          
    - name: deploy dockerfile
      uses: appleboy/scp-action@master  
      with:
          host: ${{ secrets.REMOTE_IP }}
          username: ${{ secrets.REMOTE_SSH_ID }}
          key: ${{ secrets.REMOTE_SSH_KEY }}
          port: ${{ secrets.REMOTE_SSH_PORT }}
          source: "dockerfile"
          strip_components: 1
          target: "/home/ubuntu/sign-app"
            
